---
# Response: holds motor configurations defined in the .yaml config file

# All arrays in this message should have the same length, or be empty.

std_msgs/Header header
string[] motor_ports
string[] motor_types
string[] motor_names
string[] motor_mimic_names
float64[] motor_mimic_gear_ratios
bool[] invert_directions